graphql_compose.fragments:
  path: "/admin/config/graphql_compose/fragments"
  defaults:
    _form: '\Drupal\graphql_compose_fragments\Form\FragmentsForm'
    _title: "GraphQL Compose Fragments"
  requirements:
    _permission: "administer graphql configuration"
  options:
    _admin_route: TRUE
