graphql.graphql_servers.*:
  type: config_entity
  label: 'Server'
  mapping:
    name:
      type: string
      label: 'Name'
    label:
      type: string
      label: 'Label'
    endpoint:
      type: string
      label: 'Endpoint'
    debug_flag:
      type: integer
      label: 'Debug Flag'
    schema:
      type: string
      label: 'Schema'
    caching:
      type: boolean
      label: 'Caching'
    batching:
      type: boolean
      label: 'Batching'
    disable_introspection:
      type: boolean
      label: 'Disable Introspection'
    query_depth:
      type: integer
      label: 'Max query depth'
    query_complexity:
      type: integer
      label: 'Max query complexity'
    schema_configuration:
      type: 'graphql.schema.[%parent.schema]'
    persisted_queries_settings:
      type: sequence
      label: 'Persisted queries settings'
      orderby: key
      sequence:
        type: plugin.plugin_configuration.persisted_query.[%key]
        label: 'The configuration for a single persisted query plugin.'

graphql.schema.*:
  type: mapping
  label: 'Schema settings'

graphql.schema.composable:
  type: mapping
  label: 'Composable schema'
  mapping:
    composable:
      type: mapping
      label: 'Composition'
      mapping:
        extensions:
          label: Enabled extensions
          type: sequence
          sequence:
            type: string

graphql.default_persisted_query_configuration:
  type: mapping
  label: 'Persisted query settings'
  mapping:
    weight:
      type: integer
      label: 'The weight'

plugin.plugin_configuration.persisted_query.*:
  type: graphql.default_persisted_query_configuration

graphql.settings:
  type: config_object
  label: "GraphQL Settings"
  mapping:
    # @todo Remove in GraphQL 5.
    dataproducer_populate_default_values:
      type: boolean
      label: "Populate dataproducer context default values"
      description: "Legacy setting: Populate dataproducer context default values before executing the resolve method. Set this to true to be future-proof. This setting is deprecated and will be removed in a future release."
