include:
  ################
  # DrupalCI includes:
  # As long as you include this, any future includes added by the Drupal Association will be accessible to your pipelines automatically.
  # View these include files at https://git.drupalcode.org/project/gitlab_templates/
  ################
  - project: $_GITLAB_TEMPLATES_REPO
    ref: $_GITLAB_TEMPLATES_REF
    file:
      - '/includes/include.drupalci.main.yml'
      - '/includes/include.drupalci.variables.yml'
      - '/includes/include.drupalci.workflows.yml'

################
# Pipeline configuration variables
#
# These are the variables provided to the Run Pipeline form that a user may want to override.
#
# Docs at https://git.drupalcode.org/project/gitlab_templates/-/blob/1.3.x-latest/includes/include.drupalci.variables.yml
################
variables:
  OPT_IN_TEST_PREVIOUS_MAJOR: 1
  OPT_IN_TEST_NEXT_MINOR: 1
  _PHPUNIT_CONCURRENT: 1
  _LENIENT_ALLOW_LIST: "address,block_field,double_field,entity_reference_revisions,eck,geofield,graphql,layout_paragraphs,menu_item_extras,metatag,paragraphs,redirect,schema_metatag,social_media_links,svg_image,token,typed_data,viewfield"

phpcs:
  allow_failure: false

phpstan:
  allow_failure: false

