<?php

/**
 * @file
 * GraphQL Compose Preview Installer.
 */

declare(strict_types=1);

use Drupal\Core\Database\Database;

/**
 * Implements hook_update_N().
 *
 * Remove the separate preview_token field from betas.
 */
function graphql_compose_preview_update_10001() {
  $schema = Database::getConnection()->schema();

  if ($schema->fieldExists('key_value_expire', 'preview_token')) {
    $schema->dropField('key_value_expire', 'preview_token');
  }
}
